README.md, SwiftyInsta/API/Constants/URLs.swift, SwiftyInsta/API/Services/APIHandler.swift, SwiftyInsta/Classes/Models/FriendshipStatusModel.swift, SwiftyInstaTests/SwiftyInstaTests.swift
=> follow/unfollow feature added.

SwiftyInsta/Classes/Models/TrayModel.swift
Added `muted` `Optional<Bool>` property in _story_ `TrayModel`.
=> Added `muted` on `TrayModel`

.travis.yml, README.md, SwiftyInsta.macOS/Info.plist, SwiftyInsta.macOS/SwiftyInsta_macOS.h, SwiftyInsta.macOSTests/Info.plist, SwiftyInsta.macOSTests/SwiftyInsta_macOSTests.swift, SwiftyInsta.podspec, SwiftyInsta.tvOS/Info.plist, SwiftyInsta.tvOS/SwiftyInsta_tvOS.h, SwiftyInsta.tvOSTests/Info.plist, SwiftyInsta.tvOSTests/SwiftyInsta_tvOSTests.swift, SwiftyInsta.watchOS/Info.plist, SwiftyInsta.watchOS/SwiftyInsta_watchOS.h, SwiftyInsta.xcodeproj/project.pbxproj, SwiftyInsta/API/Services/APIHandler.swift, SwiftyInsta/API/Services/MediaHandler.swift, SwiftyInsta/API/Services/ProfileHandler.swift, SwiftyInsta/API/Services/StoryHandler.swift, SwiftyInsta/Classes/Models/NameTagModel.swift, SwiftyInsta/Classes/Models/RecentActivitiesModel.swift, SwiftyInsta/Classes/Models/TrayModel.swift, SwiftyInsta/Classes/Models/UploadMediaModel.swift, SwiftyInsta/Helpers/CryptoHelper.swift, SwiftyInsta/Supporting Files/SwiftyInsta.h, SwiftyInsta/Web/LoginWebView.swift
I've changed the definitions so that the library will no longer be `iOS` only. 
I still need to test it though.
I will push it for review as soon as I get it done.
- added multiple _platform-specific_ targets
=> Add `macOS`, `tvOS` and `watchOS` compatibility

SwiftyInsta/API/Constants/URLs.swift, SwiftyInsta/API/Services/APIHandler.swift, SwiftyInsta/API/Services/StoryHandler.swift, SwiftyInsta/Classes/Models/StoryModel.swift, SwiftyInsta/Classes/Models/TrayModel.swift
Merging all the changes added in `1.7.*` since the creation of the `development` branch into it, adjusting for the new syntax, etc.
=> Merge `1.*` changes into `2.0`

SwiftyInsta.podspec, SwiftyInsta/API/Constants/URLs.swift, SwiftyInsta/API/Services/APIHandler.swift, SwiftyInsta/API/Services/StoryHandler.swift, SwiftyInsta/Classes/Models/StoryModel.swift
=> Add pagination for `StoryViewers`

SwiftyInsta.podspec, SwiftyInsta/Web/InstagramLoginWebViewDelegate.swift
Addressing #75 and #76.
`completionHandler` in `create` should not be `Optional`.
=> Fix `InstagramLoginWebView` force unwrapping `nil`

.travis.yml, SwiftyInsta.xcodeproj/project.pbxproj, SwiftyInsta/Helpers/PaginationHelper.swift, SwiftyInsta/Local/Authentication/Authentication.swift, SwiftyInsta/Local/Responses/CommentResponse.swift, SwiftyInsta/Local/Responses/MediaResponse.swift, SwiftyInsta/Local/Responses/ParsedResponse.swift, SwiftyInsta/Local/Responses/StoryResponse.swift, SwiftyInsta/Local/Responses/ThreadResponse.swift, SwiftyInsta/Local/Responses/UserResponse.swift, SwiftyInsta/UI/LoginWebViewController.swift
For now, everything was Xcode 11 only in `2.0`.
I'll try and fix it with these commits.
=> Add back Xcode 10 support

SwiftyInsta.podspec, SwiftyInsta.xcodeproj/project.pbxproj, SwiftyInsta/API/Endpoints/CommentHandler.swift, SwiftyInsta/API/Endpoints/MediaHandler.swift, SwiftyInsta/API/Endpoints/ProfileHandler.swift, SwiftyInsta/API/Endpoints/StoryHandler.swift, SwiftyInsta/Helpers/HTTPHelper.swift, SwiftyInsta/Local/Requests/DynamicRequest.swift, SwiftyInsta/Local/Responses/DynamicResponse.swift
Improve signed requests management and `DynamicRequest` (now preserving case, vs. `DynamicResponse` always changing to _camelCase_).
+ `reelsMedia` is not working (Instagram changes?)
=> Fix signed requests

SwiftyInsta/API/Constants/Headers.swift
@TheM4hd1 suggestion.
It has not been tested, so pr-ing to `development`.
=> Update `igSignatureVersionValue` to `5`

SwiftyInsta.xcodeproj/project.pbxproj, SwiftyInsta/Local/Responses/MediaResponse.swift, SwiftyInsta/Local/Responses/StoryLocationResponse.swift
Closes #99.
As always, I forgot to bump CocoaPods version 🙈
=> Add `StoryLocation` response

SwiftyInsta.podspec, SwiftyInsta/API/Endpoints/UserHandler.swift, SwiftyInsta/Local/Responses/UserResponse.swift
Small improvements as described in #107
=> Improve on `friendshipRequest`

SwiftyInsta.podspec, SwiftyInsta/API/Handlers/FeedHandler.swift, SwiftyInsta/Helpers/PaginationHelper.swift
Thanks to @RealOlympusDev (#135).
=> Fix timeline and pagination

SwiftyInsta.podspec, SwiftyInsta/UI/LoginWebView.swift, SwiftyInsta/UI/LoginWebViewController.swift
=> Add custom user agent support for `LoginWebView`

SwiftyInsta.podspec, SwiftyInsta/UI/LoginWebView.swift, SwiftyInsta/UI/LoginWebViewController.swift
Reverts TheM4hd1/SwiftyInsta#156
=> Revert "Add custom user agent support for `LoginWebView`"

SwiftyInsta/Helpers/PaginationHelper.swift, SwiftyInsta/Helpers/PaginationParameters.swift
=> Fix `PaginationParameters` bug

SwiftyInsta/API/Client/APIHandler.swift, SwiftyInsta/API/Constants/Headers.swift, SwiftyInsta/API/Handlers/StoryHandler.swift, SwiftyInsta/API/Handlers/UserHandler.swift, SwiftyInsta/Local/Devices/Device.swift, SwiftyInsta/Local/Responses/UserResponse.swift, SwiftyInsta/UI/LoginWebView.swift
New `User-Agent`'s fixed `Google Play` header and LoginWebView related issues like  #173 
Added some missing properties to `UserResponse` like follow counts, profile context vs..
Added `Highlighted Stories` request
=> Added new matched `User-Agent`'s, `Highlighted Stories` and some `UserResponse` properties

SwiftyInsta.podspec, SwiftyInsta/API/Constants/Headers.swift, SwiftyInsta/API/Endpoints/Endpoint.swift, SwiftyInsta/API/Endpoints/EndpointPath.swift, SwiftyInsta/API/Endpoints/EndpointRepresentable.swift, SwiftyInsta/API/Handlers/MediaHandler.swift, SwiftyInsta/Local/Responses/UploadResponse.swift
Tested it a few times and worked fine. a little messy but you can use it for now.
#206
=> Upload function for Photo

SwiftyInsta.podspec, SwiftyInsta/API/Endpoints/Endpoint.swift, SwiftyInsta/API/Handlers/MediaHandler.swift, SwiftyInsta/Helpers/HTTPHelper.swift
updated `like_media` function with latest instagram changes.
=> updated like function

SwiftyInsta.podspec, SwiftyInsta/API/Endpoints/Endpoint.swift, SwiftyInsta/API/Handlers/UserHandler.swift
=> Updated UserHandler.current function

SwiftyInsta.podspec, SwiftyInsta.xcodeproj/project.pbxproj, SwiftyInsta/API/Client/APIHandler.swift, SwiftyInsta/API/Endpoints/Endpoint.swift, SwiftyInsta/API/Handlers/MediaHandler.swift, SwiftyInsta/Local/Authentication/Authentication.swift, SwiftyInsta/Local/Requests/Legacy/UploadMediaModel.swift, SwiftyInsta/Local/Requests/UploadRequest.swift, SwiftyInsta/Local/Responses/UploadResponse.swift, SwiftyInsta/UI/LoginWebView.swift, SwiftyInsta/UI/LoginWebViewController.swift
- fix for `media.upload(video:completionHandler)` and updated with recent instagram changes
- fix for `LoginWebView` issue on `iOS 11`
=> Upload Video Fixed

SwiftyInsta.podspec, SwiftyInsta/API/Handlers/AuthenticationHandler.swift
- Fixed a bug which lib were not able to detect login errors
=> Fixed Login Error Parsing

Package.swift, SwiftyInsta/API/Handlers/MessageHandler.swift
Thanks for the feedback @sbertix, I think this should be ok.
=> Fixed pagination support for Inbox
